### ISSUE TITLE
Landing Page Content

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#22]
We need to decide what all we want on the home/landing page after logging in. Currently I have push list items and custom announcements, but to do that we'd need to support that in the data. I don't really care what the answer is, just need to decide on one.

**Comment by joelmeister** [comment]
I can get going on that, but I think for right now the landing page would be:

if user has cart, 
         shopping cart
else
         order page

**Comment by c-topherl** [comment]
That's fine, but I think no matter which route we go, the content for the landing page should really just be the response to logging in successfully so we don't have to make another request in between those pages loading.

**Comment by joelmeister** [comment]
I think that's a good idea but make that lower priority for now.  Functionality would seem more important than one extra http request

**Comment by c-topherl** [comment]
function logIn(username, password)
    if (loginSuccessful(username,password)
        getLandingPage(customer)
    else
        return JSON error

function getLandingPage(cust):
    if (COUNT(SELECT \* FROM CART WHERE CUSTOMER=cust) > 0)
        getCart(cust)
    else
        getDeliveryOptions(cust)

**Comment by joelmeister** [comment]
Ok done, it returns either the cart contents, or everything from the product_unit table.  I will need to update the db article as well because I changed a few more things.  

Another thought here, eventually we may want to make this landing page configurable to the users i.e. let them pick where they land.   That would be a setting we add to the user_settings table.  That is, unless the breweries always want to go to this "push list" page that isn't available yet.  Maybe we need to come up with a main control file for them just like CT.

**Comment by joelmeister** [comment]
Closed.  Create a new issue for other changes.
