### ISSUE TITLE
add_cart_header

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#34]
1) Can we make "type" (delivery method) something a little more descriptive? Like delivery_method?

2) Why is user_id required? I would think orders against customer codes is sufficient.

3) What kind of value are you expecting for type/delivery method? Are there codes for each kind? Or are we passing raw strings? Passing raw strings (type: pickup) seems like it's asking for mismatches (type: pick-up, type: Pick Up), but maybe not.

4) Do we need shipping_type right now? Can we leave that out for the base product?

**Comment by joelmeister** [comment]
1) yes
2) just discussed this.  makes the system more robust + not really extra time to develop (since i did it this way already)
3) I will make this a table and just use an integer id.  Are there any other delivery methods other than pickup/delivery?  
4) yea, fine with me.  i'll update the code to stop passing it, but I am going to leave it in the DB.  Thinking about it now, we can probably roll "shipping type" in to delivery methods i.e. 

+----+------+-------------------+
| id | code | description       |
+----+------+-------------------+
|  1 | pu   | Pick-up           |
|  2 | stnd | Standard Delivery |
|  3 | 1day | One Day Delivery  |
+----+------+-------------------+

.  thoughts?

**Comment by joelmeister** [comment]
Created delivery_methods table and updated other columns

**Comment by c-topherl** [comment]
What you outlined works for me (combining shipping type with delivery method).
